name: strapi_populate_builder
description: Converts nested Strapi populate JSON into REST-compatible query strings.
version: 1.0.0
repository: https://github.com/AlexeyShevchenko/strapi_populate_builder
license: MIT

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
